# Generated by Django 5.2.16 on 2026-07-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('comuna', models.CharField(blank=True, max_length=80, verbose_name='Comuna')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('cotizado', 'Cotización enviada'), ('cerrado', 'Cerrado / Vendido'), ('descartado', 'Descartado')], default='nuevo', max_length=20)),
                ('notas_internas', models.TextField(blank=True, help_text='Uso interno. No lo ve el cliente.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='servicios.servicio', verbose_name='Servicio de interés')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-creado'],
            },
        ),
    ]
