# Generated by Django 5.2.16 on 2026-07-14 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='bi-window', help_text='Clase de Bootstrap Icons. Ej: bi-car-front-fill', max_length=50)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('descripcion_corta', models.CharField(help_text='Se muestra en la tarjeta del listado.', max_length=200)),
                ('descripcion', models.TextField(help_text='Texto completo de la página de detalle.')),
                ('beneficios', models.TextField(blank=True, help_text='Un beneficio por línea.')),
                ('imagen', models.ImageField(blank=True, upload_to='servicios/')),
                ('destacado', models.BooleanField(default=False, help_text='Aparece en la portada.')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='servicios.categoria')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['categoria__orden', 'orden', 'nombre'],
            },
        ),
    ]
