# Generated by Django 5.2.16 on 2026-07-14 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Categoría del blog',
                'verbose_name_plural': 'Categorías del blog',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, verbose_name='Título')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('extracto', models.CharField(help_text='Resumen breve. Se muestra en el listado y en Google.', max_length=220, verbose_name='Extracto')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, upload_to='blog/%Y/%m/', verbose_name='Imagen destacada')),
                ('alt', models.CharField(blank=True, help_text='Si lo dejas vacío se usa el título.', max_length=160, verbose_name='Texto alternativo')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=20)),
                ('publicado', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.categoriapost')),
                ('servicio_relacionado', models.ForeignKey(blank=True, help_text='El artículo cierra ofreciendo este servicio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos (Tips)',
                'ordering': ['-publicado'],
                'indexes': [models.Index(fields=['-publicado'], name='blog_post_publica_176893_idx')],
            },
        ),
    ]
