# Generated by Django 5.2.16 on 2026-07-14 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=140, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Opcional. Ej: "Oficina en Providencia, 40 m² de control solar."', verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='galeria/%Y/%m/', verbose_name='Foto')),
                ('alt', models.CharField(blank=True, help_text='Describe la foto para buscadores y lectores de pantalla. Si lo dejas vacío se usa el título.', max_length=160, verbose_name='Texto alternativo')),
                ('ubicacion', models.CharField(blank=True, max_length=100, verbose_name='Comuna / Lugar')),
                ('fecha_trabajo', models.DateField(blank=True, null=True, verbose_name='Fecha del trabajo')),
                ('destacado', models.BooleanField(default=False, help_text='Aparece en la portada.')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos', to='servicios.servicio', verbose_name='Servicio aplicado')),
            ],
            options={
                'verbose_name': 'Trabajo',
                'verbose_name_plural': 'Galería de trabajos',
                'ordering': ['orden', '-fecha_trabajo', '-creado'],
            },
        ),
    ]
